# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ERS
                                 A QGIS plugin
 Earth remote sensing
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-20
        copyright            : (C) 2024 by Artem Kovalev
        email                : artem17404@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ERS class from file ERS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .earth_remote_sensing import ERS
    return ERS(iface)
